# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SHIMCOcamWidgets.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Application(object):
    def __init__(self, SHIMCOcamWidgets):
        self.SHIMCOcamWidgets = SHIMCOcamWidgets
        self.ui = uic.loadUi('SHIMCOcamWidgets.ui')
        self.ui.SetValues.clicked.connect(self.values)
        self.ui.show()
        self.run()
    def run(self):
        self.SHIMCOcamWidgets.exec_()
    def values(self):
        Framerate = self.ui.FRSpinbox.text()
        print('Framerate', Framerate)
        


if __name__ == "__main__":
    import sys
    SHIMCOcamWidgets = QtWidgets.QApplication(sys.argv)
    Application(SHIMCOcamWidgets)

